# Generated by Django 5.2.17 on 2026-08-21 12:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevisionMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tool_type', models.CharField(choices=[('flashcards', 'Flashcards'), ('concept_sheet', 'Concept sheet'), ('quiz', 'Quiz'), ('video', 'Video')], max_length=20)),
                ('weakness_type', models.CharField(choices=[('recall', 'Recall'), ('conceptual', 'Conceptual'), ('procedural', 'Procedural')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('content_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revision_materials', to='curriculum.topic')),
            ],
        ),
        migrations.CreateModel(
            name='StudentRevisionRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('recommended', 'Recommended'), ('started', 'Started'), ('completed', 'Completed')], default='recommended', max_length=15)),
                ('recommended_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('revision_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='revision.revisionmaterial')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='accounts.studentprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['student', 'status'], name='revision_st_student_6e1e83_idx')],
            },
        ),
    ]
