# Generated by Django 5.2.17 on 2026-08-21 12:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('classroom', '0001_initial'),
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assignment_type', models.CharField(choices=[('classwork', 'Classwork'), ('homework', 'Homework'), ('test', 'Test'), ('exam', 'Exam')], max_length=20)),
                ('photo', models.ImageField(upload_to='submissions/%Y/%m/')),
                ('question_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('marked', 'Marked'), ('needs_review', 'Needs review')], default='processing', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('marked_at', models.DateTimeField(blank=True, null=True)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='classroom.schoolclass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='accounts.studentprofile')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='curriculum.unit')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_submissions', to='accounts.teacherprofile')),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_number', models.PositiveIntegerField()),
                ('student_answer', models.TextField(blank=True)),
                ('expected_answer', models.TextField(blank=True)),
                ('ai_is_correct', models.BooleanField(null=True)),
                ('ai_confidence', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('teacher_overridden', models.BooleanField(default=False)),
                ('final_is_correct', models.BooleanField(null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_questions', to='accounts.teacherprofile')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='submissions.submission')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submission_questions', to='curriculum.topic')),
            ],
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['student', 'status'], name='submissions_student_c504ac_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['school_class'], name='submissions_school__e69d14_idx'),
        ),
        migrations.AddIndex(
            model_name='submissionquestion',
            index=models.Index(fields=['topic'], name='submissions_topic_i_18d941_idx'),
        ),
        migrations.AddConstraint(
            model_name='submissionquestion',
            constraint=models.UniqueConstraint(fields=('submission', 'question_number'), name='uniq_submission_question_number'),
        ),
    ]
