# Generated by Django 5.2.17 on 2026-08-21 12:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ClassTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.teacherprofile')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('year_level', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='accounts.school')),
                ('students', models.ManyToManyField(related_name='classes', through='classroom.ClassStudent', to='accounts.studentprofile')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='curriculum.subject')),
                ('teachers', models.ManyToManyField(related_name='classes', through='classroom.ClassTeacher', to='accounts.teacherprofile')),
            ],
        ),
        migrations.AddField(
            model_name='classteacher',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.schoolclass'),
        ),
        migrations.AddField(
            model_name='classstudent',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.schoolclass'),
        ),
        migrations.AddConstraint(
            model_name='classteacher',
            constraint=models.UniqueConstraint(fields=('school_class', 'teacher'), name='uniq_class_teacher'),
        ),
        migrations.AddConstraint(
            model_name='classstudent',
            constraint=models.UniqueConstraint(fields=('school_class', 'student'), name='uniq_class_student'),
        ),
    ]
