# Generated by Django 5.2.17 on 2026-08-22 07:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.PositiveSmallIntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_slots', to='classroom.schoolclass')),
            ],
            options={
                'indexes': [models.Index(fields=['school_class'], name='classroom_c_school__fdbe8d_idx'), models.Index(fields=['day_of_week'], name='classroom_c_day_of__9dda8a_idx')],
            },
        ),
    ]
