# Generated by Django 5.2.17 on 2026-08-21 12:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('revision', '0001_initial'),
        ('submissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('submission_marked', 'Submission marked'), ('tool_started', 'Tool started'), ('tool_completed', 'Tool completed'), ('profile_updated', 'Profile updated')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('related_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='revision.revisionmaterial')),
                ('related_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='submissions.submission')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_events', to='accounts.studentprofile')),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['student', '-occurred_at'], name='activitylog_student_5b02d5_idx')],
            },
        ),
    ]
