# Generated by Django 5.2.17 on 2026-08-21 12:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSubjectProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assignments_count', models.PositiveIntegerField(default=0)),
                ('profile_generated', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('recommended_focus_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='curriculum.topic')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_profiles', to='accounts.studentprofile')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_profiles', to='curriculum.subject')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('student', 'subject'), name='uniq_student_subject')],
            },
        ),
        migrations.CreateModel(
            name='StudentTopicStat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('classification', models.CharField(choices=[('strong', 'Strong'), ('weak', 'Weak'), ('neutral', 'Neutral')], default='neutral', max_length=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_stats', to='accounts.studentprofile')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_stats', to='curriculum.topic')),
            ],
            options={
                'indexes': [models.Index(fields=['topic', 'classification'], name='profiles_st_topic_i_92f894_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'topic'), name='uniq_student_topic')],
            },
        ),
    ]
